# Generated by Django 2.2.6 on 2019-12-29 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id',
        ),
        migrations.AlterField(
            model_name='person',
            name='id_num',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
