# Generated by Django 2.2.6 on 2020-01-08 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191229_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='person',
            name='house_num',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='province',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='street_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='town',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='zip_code',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
