# Generated by Django 2.2.6 on 2020-01-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200108_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='house_num',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='province',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='street_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='town',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='person',
            name='zip_code',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
