# Generated by Django 2.2.6 on 2020-01-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200109_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.DateField(),
        ),
    ]
