# Generated by Django 2.2.6 on 2020-01-09 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200109_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateOfBirth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='born',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.DateOfBirth'),
        ),
    ]
