# Generated by Django 2.2.6 on 2020-01-09 23:44

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200109_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id_pic',
            field=models.ImageField(upload_to=accounts.models.person_directory_with_uuid),
        ),
    ]
