# Generated by Django 2.2.6 on 2020-01-12 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200109_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='id_pic',
        ),
    ]
