# Generated by Django 2.2.6 on 2020-01-20 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_person_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='pic',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
